export const PROJECTS = [
    {
        projectName: 'Stellr',
        projectWebsite: 'https://stellr.social',
        projectRepoLink: 'https://github.com/0xDreamLabs/stellr',
        projectDescription: `Stellr.social is a Web 3.0 social networking application being built on Polygon via Lens Protocol, NextJS, React18, Tailwind V3, Typescript, EthersJS, Solidity, AWS Amplify and Multilingual support. Stellr's mission is to empower creators by enabling them to have the ability to grow and scale their network as well as monetize their content. We are hooping to launch the Stellr MVP in the coming months. Checkout out the discord to find out more.`, 
        projectImageUrl: '/Images/projectImages/stellrProject.webp',
        projectLabelYear: 'Soon',
        omitDivider: false,
    },
    {
        projectName: 'Leverage Trading Calculator',
        projectWebsite: 'https://leveragetradingcalculator.com',
        projectRepoLink: 'https://github.com/0xD4V1NC1/leverage-trading-calculator',
        projectDescription: `Leverage Trading Calculator is a tool I built to help me estimate entry and exit points on leveraged crypto trades. It is built with React 18, NextJS, TailwindCSS v3, and TypeScript. This very simple project bolsters a perfect lighthouse score in all categories `, 
        projectImageUrl: '/Images/projectImages/ltcProject.webp',
        projectLabelYear: '2022',
        omitDivider: false,
    },
    {
        projectName: '0xWolfpack Finance NFT',
        projectWebsite: 'https://pl7yg-5aaaa-aaaad-qbwiq-cai.ic.fleek.co/',
        projectRepoLink: 'https://github.com/0xD4V1NC1/nft-minting-site',
        projectDescription: `0xWF NFT is a Web3.0 NFT minting dapp built on the polygon network with React 18, TailwindCSS v3, Solidity 0.8.4, Mocha Testing Framework, TypeScript and Storybook`, 
        projectImageUrl: '/Images/projectImages/0xWFNFT.webp',
        projectLabelYear: '2022',
        omitDivider: false,
    },
    {
        projectName: 'Endeavors.tv',
        projectWebsite: 'https://Endeavors.tv',
        projectRepoLink: '',
        projectDescription: `Endeavors.tv previously known as Sleepless Gamers is a live streaming platform that was built with the intent of solving low volume viewership for entry level streamers. This platform was originally built with React, GoLang, JS, and TailwindCSS but is now running on Svelte, TypeScript, TailwindCSS and Rust `, 
        projectImageUrl: '/Images/projectImages/sleeplessGamersProject.webp',
        projectLabelYear: '2021',
        omitDivider: false,
    },
    {
        projectName: 'NextJS Social',
        projectWebsite: 'https://next-js-social-media-app.herokuapp.com/',
        projectRepoLink: 'https://github.com/davidhanlon23/nextJS-social-media-app',
        projectDescription: `NextJS Social is a fully functional demo social media application that I built using React, NextJS, ExpressJS, and MongoDB/NoSQL in order to practice building projects with Server Side Rendering.`, 
        projectImageUrl: '/Images/projectImages/nextJsProject.webp',
        projectLabelYear: '2019',
        omitDivider: false,
    },
    {
        projectName: 'Original Portfolio',
        projectWebsite: 'https://davidmhanlon-stg.herokuapp.com/',
        projectRepoLink: 'https://github.com/davidhanlon23/DavidHanlonPortfolio',
        projectDescription: `My original website portfolio was built using ReactJS, JS, BootstrapCSS, ExpressJS and MongoDB/NoSql. This site is currently hosted on the Heroku platform.`, 
        projectImageUrl: '/Images/projectImages/davidHPortfolio.webp',
        projectLabelYear: '2019',
        omitDivider: false,
    },
    {
        projectName: 'Love Calculator',
        projectWebsite: 'https://lovecalculator-bb0e8.web.app/',
        projectRepoLink: 'https://github.com/davidhanlon23/loveCalculator',
        projectDescription: `Love Calculator is a progressive web app I built for fun to better understand using Ionic's hybrid mobile application framework. The calculator takes the sum of the ASCII value of the two inputs and runs it through a function that calculates the "percent love" of two individuals. This project was built with JS, Angular, and Ionic's Mobile Framework hosted with firebase`, 
        projectImageUrl: '/Images/projectImages/loveCalculatorProject.webp',
        projectLabelYear: '2016',
        omitDivider: false,
    },
  
    {
        projectName: 'Expense Tracker',
        projectWebsite: '',
        projectRepoLink: 'https://github.com/davidhanlon23/ExpenseTracker',
        projectDescription: `Expense Tracker is a simple app to record and keep track of your recent transactions. This app was built using Ionic Hybrid Mobile Application Framework, and AngularJS.`, 
        projectImageUrl: '/Images/projectImages/expenseTrackerProject.webp',
        projectLabelYear: '2016',
        omitDivider: false,
    },
     {
        projectName: 'Chat App',
        projectWebsite: '',
        projectRepoLink: 'https://github.com/davidhanlon23/ChatApp',
        projectDescription: `Chat App is a chat application built using Firebase Authentication, Angular, Ionic Hybrid Mobile Application Framework and ExpressJS. Simple app that allowed multiple users to converse in a single chat room. `, 
        projectImageUrl: '/Images/projectImages/chatAppProject.webp',
        projectLabelYear: '2016',
        omitDivider: true,
    },

];