export { default as Testimonials } from './testimonials';
export { default as DefaultHero } from './hero/default-hero';
export { default as LiveHero } from './hero/live-hero';
export { default as CryptoHero } from './hero/crypto-hero';
export { default as Showcase } from './showcase';
export { default as Education } from './education';
export { default as Experience } from './experience';
export { default as Contact } from './contact';
export { default as About } from './about';